version: '3.4'

services:
  tiendaservicio.api.autor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6104:80"

  tiendaservicio.api.libro:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6105:80"


  tiendaservicio.api.carritocompra:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Libros=http://tiendaservicio.api.libro
      - Services__Autores=http://tiendaservicio.api.autor
    ports:
      - "6106:80"

