version: '3.4'

services:
  tiendaservicio.api.autor:
    image: ${DOCKER_REGISTRY-}tiendaservicioapiautor
    build:
      context: .
      dockerfile: TiendaServicio.Api.Autor/Dockerfile

  tiendaservicio.api.libro:
    image: ${DOCKER_REGISTRY-}tiendaservicioapilibro
    build:
      context: .
      dockerfile: TiendaServicio.Api.Libro/Dockerfile
  tiendaservicio.api.carritocompra:
    image: ${DOCKER_REGISTRY-}tiendaservicioapicarritocompra
    build:
      context: .
      dockerfile: TiendaServicio.Api.CarritoCompra/Dockerfile

networks:
  default:
    external:
      name: microservicenet
